added non-live mode

diff --git a/usr/bin/eliveremote b/usr/bin/eliveremote
--- a/usr/bin/eliveremote
+++ b/usr/bin/eliveremote
@@ -369,6 +369,29 @@ main(){
             sudo /etc/init.d/ssh start
         fi
 
+    else
+
+        if [[ -n "$DISPLAY" ]] ; then
+
+	    result="$( $guitool --entry --text="$( eval_gettext "Insert your root (admin) password, we need to know it for be able to connect" )" || echo cancel )"
+	    # verify
+	    if [[ "${result}" = "cancel" ]] || [[ -z "$result" ]] ; then
+		$guitool --error --text="$( eval_gettext "We cannot connect to your computer if we don't know the password to use" )"
+		exit
+	    fi
+	    pass_root="$result"
+
+        else
+            echo ; echo 'Enter the new password for root (hidden)' ; echo 'You need to give this password to the admin in order to connect' ; echo ; echo ; sudo passwd
+        fi
+
+        # no ssh running
+        if ! ps aux | grep -v grep | grep -q "root.*bin.*sshd" ; then
+	    for i in 1 2 3 4 5 6
+	    do
+		gksu /etc/init.d/ssh start && break
+	    done
+        fi
     fi
 
 
