auto: untarzanice | PLEASE review this commit @Thanatermesis

diff --git a/usr/bin/eliveremote b/usr/bin/eliveremote
--- a/usr/bin/eliveremote
+++ b/usr/bin/eliveremote
@@ -258,7 +258,7 @@ connection_stablish(){
 
 
                             local translated_message
-                            translated_message="$( printf "$( eval_gettext "Information sent in a private message to %s on the IRC chat, please make sure he is connected or he will not receive the info and cannot assist you, note that this message is sent successfully only if the chat was able to connect to the elive room, otherwise try to connect again or do it manually" )" "$SURGEON_NICK" )"
+                            translated_message="$( printf "$( eval_gettext "Information sent in a private message to %s on the IRC chat, make sure that person is connected or will not receive the info and so then cannot assist you. Note that this message is sent successfully only if the chat was able to connect to the Elive room, otherwise try to connect again or give the info manually" )" "$SURGEON_NICK" )"
 
                             $guitool --info --text="$translated_message"
                         fi
@@ -279,7 +279,7 @@ connection_stablish(){
 
 
                         local translated_message
-                        translated_message="$( printf "$( eval_gettext "Please open your chat application (second icon of your dock bar) and contact %s. Tell him your root password and the port number '%s' in a private chat (right click on him)" )" "$SURGEON_NICK" "$port_local" )"
+                        translated_message="$( printf "$( eval_gettext "Please open your chat application (second icon in your dock bar) and contact %s. Tell him your root password and the port number '%s' in a private chat (right click on him)" )" "$SURGEON_NICK" "$port_local" )"
 
                         $guitool --info --text="$translated_message"
                     fi
@@ -307,7 +307,7 @@ connection_stablish(){
                         sleep 1
                     done
 
-                    $guitool --info --text="$( eval_gettext "We are going to open a shared terminal, please maximize this window after it opens, and do not close it until the remote assistance finished. Somebody is working from it, please do not type in the terminal. Otherwise you will make his work more difficult." )"
+                    $guitool --info --text="$( eval_gettext "We are going to open a shared terminal, please maximize this window after it opens, and do not close it until the remote assistance finished. Somebody will be working from it, please do not type in the terminal. Otherwise you will make his work more difficult." )"
                     gksu "urxvt -e bash -c 'tmux attach'" &
                 fi
 
@@ -393,7 +393,7 @@ main(){
                 el_dependencies_check "gksu"
                 gksu /etc/init.d/ssh start
             else
-                el_error "$( eval_gettext "You need to install ssh and have it running first" )"
+                el_error "$( eval_gettext "You need to install SSH and have it running first" )"
             fi
         fi
     fi
@@ -410,7 +410,7 @@ main(){
 
     # check if our ssh is set up {{{
     if [[ -n $DISPLAY ]] ; then
-        $guitool --question --text="$( eval_gettext "This tool allows you to have remote assistance from an Elive developer in a secure way, giving him access to your computer. Continue?" )" || exit
+        $guitool --question --text="$( eval_gettext "This tool allows you to have remote assistance from an Elive developer in a secure way, giving him access to your computer. Do you want to continue?" )" || exit
     else
         echo -e "$( eval_gettext "This tool gives you remote assistance from an Elive developer in a secure way, giving him access to your computer." )"
 
@@ -443,7 +443,7 @@ main(){
 
         else
             local message_type_root_pass
-            message_type_root_pass="$( printf "$( eval_gettext "Enter the new password for root (admin), what you type is hidden:" )" "" )"
+            message_type_root_pass="$( printf "$( eval_gettext "Enter the new password for root (admin), what you type will be hidden:" )" "" )"
             local message_type_root_pass_details
 
             sudo passwd
@@ -461,7 +461,7 @@ main(){
             result="$( $guitool --entry --text="$( eval_gettext "Insert your root (admin) password, we need to know it to be able to connect" )" || echo cancel )"
             # verify
             if [[ "${result}" = "cancel" ]] || [[ -z "$result" ]] ; then
-                $guitool --error --text="$( eval_gettext "We cannot connect to your computer if we don't know the password to use" )"
+                $guitool --error --text="$( eval_gettext "We cannot connect to your computer if we don't know the password" )"
                 exit
             fi
             pass_root="$result"
@@ -518,7 +518,7 @@ main(){
                                 echo "$SURGEON_NICK"
                                 echo "$SURGEON_NAME"
                                 echo "$SURGEON_POSITION"
-                            done 3<<< "$( ls -1 /usr/share/eliveremote/surgeons/*/profile.sh | psort -- -p "eliveadmin" -p "thanatermesis" )" | $guitool --list --width=620 --height=280 --text="$( eval_gettext "Select the person that you want to give access to your computer from the list" )" --hide-column=1 --column="" --column="$( eval_gettext "Nickname" )" --column="$( eval_gettext "Name" )" --column="$( eval_gettext "Ranked" )" || echo "cancel" )"
+                            done 3<<< "$( ls -1 /usr/share/eliveremote/surgeons/*/profile.sh | psort -- -p "eliveadmin" -p "thanatermesis" )" | $guitool --list --width=620 --height=280 --text="$( eval_gettext "Select the person from the list that you want to give access to your computer" )" --hide-column=1 --column="" --column="$( eval_gettext "Nickname" )" --column="$( eval_gettext "Name" )" --column="$( eval_gettext "Ranked" )" || echo "cancel" )"
         else
             if [[ -s "/usr/share/eliveremote/surgeons/eliveadmin1/profile.sh" ]] ; then
                 result="/usr/share/eliveremote/surgeons/eliveadmin1/profile.sh"
